/**
 * {{ObjectName}}
 * Single trigger for {{ObjectName}} object
 * 
 * ENFORCE: One trigger per object — NEVER have multiple triggers on same object
 * 
 * Architecture Notes:
 * - This trigger has ZERO logic
 * - All logic routes through handler
 * - Handler dispatches to Service layer
 * - This structure ensures:
 *   * Clear separation of concerns
 *   * Easy testing of business logic
 *   * Simplified debugging
 *   * Reusable business logic components
 * 
 * @author Generated by sfai
 * @date {{CreatedDate}}
 */
trigger {{ObjectName}} on {{ObjectName}}__c (
    before insert, after insert,
    before update, after update,
    before delete, after delete,
    after undelete
) {
    // Instantiate handler and delegate all logic
    new {{ObjectName}}TriggerHandler().handle();
}
